[book]
title = "Rust Feed"
authors = ["Suradet Pratomsak"]
language = "th"
description = "Rust Feed แหล่งรวบรวมบทความภาษา Rust ที่โพสต์ใน Facebook Rust Dev Community"

[output.html]
additional-css = ["theme/custom.css"]
site-url = "https://rust-feed.github.io/"
git-repository-url = "https://github.com/rust-feed/rust-feed.github.io"
